name: Update database
on:
  schedule:
    - cron:  '00 10 * * *'
  workflow_dispatch:
env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: robinraju/release-downloader@v1.7
        with:
          latest: true
      - name: Extract
        run: |
          tar -xvf WorldUpdator.tar.gz
          tar -xvf VillageUpdator.tar.gz
      - name: Run world updator
        run: |
          chmod +x ./WorldUpdator
          ./WorldUpdator
        working-directory: WorldUpdatorPublish
      - name: Run village updator
        run: |
          chmod +x ./VillageUpdator
          ./VillageUpdator
        working-directory: VillagedUpdatorPublish
      

    

